In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = 'SimHei' ## 设置中文显示
%matplotlib inline
# 1.加载数据
# 资产负债
data1=pd.read_csv('zcfzb_300146.csv',na_values=['--'])
data1.dropna(how='all',inplace = True)
# 利润表
data2=pd.read_csv('lrb_300146.csv',na_values=['--'])
data2.dropna(how='all',inplace = True)

In [35]:
# 查看资产负债表前五行
dz=data1[:5:]
dz

,报告日期,2019-12-31,2018-12-31,2017-12-31,2016-12-31,2015-12-31,2014-12-31,2013-12-31,2012-12-31,2011-12-31,2010-12-31,2009-12-31,2008-12-31,2007-12-31,Unnamed: 14
0,货币资金(万元),182155,181300.0,265483.0,201563.0,144364.0,153704.0,153018.0,124616.0,135106.0,150360.0,4109,2107,746,NaN
1,结算备付金(万元),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
2,拆出资金(万元),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN
3,交易性金融资产(万元),69000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,243,NaN
4,衍生金融资产(万元),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,NaN

In [ ]:
data2

In [2]:
# 资产负债分析
df_z=data1
# df_z=df_z.fillna(0)
# df_z["总价"]=df_z.sum
# 颠倒行和列
df_z.transpose()

,0,1,2,3,4,5,6,7,8,9,...,98,99,100,101,102,103,104,105,106,107
报告日期,货币资金(万元),结算备付金(万元),拆出资金(万元),交易性金融资产(万元),衍生金融资产(万元),应收票据(万元),应收账款(万元),预付款项(万元),应收保费(万元),应收分保账款(万元),...,盈余公积(万元),一般风险准备(万元),未确定的投资损失(万元),未分配利润(万元),拟分配现金股利(万元),外币报表折算差额(万元),归属于母公司股东权益合计(万元),少数股东权益(万元),所有者权益(或股东权益)合计(万元),负债和所有者权益(或股东权益)总计(万元)
2019-12-31,182155,NaN,NaN,69000,NaN,NaN,11353,7612,NaN,NaN,...,46652,NaN,NaN,69180,NaN,NaN,599217,-6078,593139,833071
2018-12-31,181300.0,NaN,NaN,NaN,NaN,2706.0,22147.0,5622.0,NaN,NaN,...,46144.0,NaN,NaN,172657.0,NaN,NaN,559179.0,129616.0,688795.0,979045.0
2017-12-31,265483.0,NaN,NaN,NaN,NaN,2659.0,15443.0,1375.0,NaN,NaN,...,35724.0,NaN,NaN,131295.0,NaN,NaN,510083.0,3113.0,513196.0,611361.0
2016-12-31,201563.0,NaN,NaN,NaN,NaN,2273.0,5439.0,2651.0,NaN,NaN,...,28253.0,NaN,NaN,100364.0,NaN,NaN,468002.0,2368.0,470370.0,532836.0
2015-12-31,144364.0,NaN,NaN,NaN,NaN,1491.0,5183.0,3320.0,NaN,NaN,...,21639.0,NaN,NaN,97137.0,NaN,NaN,456202.0,-816.0,455386.0,490541.0
2014-12-31,153704.0,NaN,NaN,NaN,NaN,2152.0,4347.0,3765.0,NaN,NaN,...,16129.0,NaN,NaN,75499.0,NaN,NaN,244770.0,NaN,244770.0,270117.0
2013-12-31,153018.0,NaN,NaN,NaN,NaN,715.0,3996.0,2253.0,NaN,NaN,...,10676.0,NaN,NaN,63500.0,NaN,NaN,223278.0,NaN,223278.0,245533.0
2012-12-31,124616.0,NaN,NaN,NaN,NaN,646.0,3695.0,7483.0,NaN,NaN,...,6281.0,NaN,NaN,38849.0,NaN,NaN,192712.0,NaN,192712.0,210473.0
2011-12-31,135106.0,NaN,NaN,NaN,NaN,627.0,2232.0,9447.0,NaN,NaN,...,3510.0,NaN,NaN,24521.0,NaN,NaN,175612.0,NaN,175612.0,189417.0
2010-12-31,150360.0,NaN,NaN,NaN,NaN,61.0,1298.0,8759.0,NaN,NaN,...,1732.0,NaN,NaN,13124.0,NaN,NaN,162437.0,NaN,162437.0,175365.0
2009-12-31,4109,0,0,0,0,15,757,910,0,0,...,884,0,0,4762,0,0,10700,0,10700,14943
2008-12-31,2107,0,0,0,0,6,768,451,0,0,...,415,0,0,13,0,0,4227,0,4227,7720
2007-12-31,746,0,0,243,0,0,364,443,0,0,...,307,0,0,957,0,0,2221,0,2221,4497
Unnamed: 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,\t\t